# Name of workflow
name: Deploy

# Trigger workflow on push and pull request to main branch
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

# Jobs to carry out
jobs:
  ci:
    name: deployToRender
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      # Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Build the server
      - name: Build the server
        run: npm run build

      # Start the server
      - name: Start the server
        run: npm run start

      # Deploy to Render
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$DEPLOY_URL"