# Name of workflow
name: Lint and Test workflow

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - develop

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      # Install dependencies with --legacy-peer-deps
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Run lint
      - name: Run Lint
        run: npm run lint

      # Run build
      - name: Run Build
        run: npm run build

      # Run tests
      - name: Run Tests
        run: npm run test