# Name of workflow
name: Deploy

# Trigger workflow on push and pull request to main branch
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

# Jobs to carry out
jobs:
  ci:
    name: deployToRender
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4.6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 3

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      # Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps --force

      # Build the server
      - name: Build the server
        run: cd server && npm run build

      # Wait for MongoDB to be healthy
      - name: Wait for MongoDB
        run: |
          until [ "`docker inspect -f {{.State.Health.Status}} $(docker ps -q --filter ancestor=mongo:latest)`" == "healthy" ]; do
            echo "Waiting for MongoDB to be healthy..."
            sleep 5
          done

      # Check Docker logs
      - name: Check Docker logs
        run: docker logs $(docker ps -q --filter "ancestor=mongo:latest")

      # Start the server
      - name: Start the server
        env:
          MONGODB_URI: mongodb://127.0.0.1:27017/techquiz
        run: cd server && npm run start

      # Deploy to Render
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$DEPLOY_URL"