# Name of workflow
name: Lint and Test workflow

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - develop

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      # Install dependencies with force
      - name: Install dependencies
        run: npm install --legacy-peer-deps --force


      # Verify dependencies
      - name: Verify dependencies
        run: npm ls

      # Build the server
      - name: Build the server
        run: npm run build

      # Run lint
      - name: Run Lint
        run: npm run lint
      
      
      # Run npm install again to resolve optional dependencies
      - name: Reinstall dependencies
        run: npm install --force

      # Run component tests
      - name: Run Component Tests
        run: npx cypress run --component --browser electron