# Name of workflow
name: Lint and Test workflow

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - develop

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      # Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Build the server
      - name: Build the server
        run: npm run build

      # Start the server
      - name: Start server
        run: npm run start &
        env:
          PORT: 3001

      # Wait for the server to be ready
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3001

      # Run lint
      - name: Run Lint
        run: npm run lint

      # Run tests
      - name: Run Tests
        run: npm run test